name: qr_secure_share
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  permission_handler: ^11.3.1
  clipboard: ^0.1.3
  # flutter_bluetooth_serial_ble: ^0.5.0
  http: ^1.2.2
  animations: ^2.0.8
  font_awesome_flutter: ^10.7.0
  file_picker: ^8.1.2
  path_provider: ^2.1.4
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  encrypt: ^5.0.3
  sqflite: ^2.3.3+1
  path: ^1.9.0
  intl: ^0.19.0
  flutter_pdfview: ^1.3.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
